# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://asifen:gWV2pIM4RzT5eZtZtipne6Q7la14aBOJ@dpg-cj97tfu3ttrc73abqleg-a.frankfurt-postgres.render.com/users_oba1?ssl=true

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
     env:
      DATABASE_URL: postgres://asifen:gWV2pIM4RzT5eZtZtipne6Q7la14aBOJ@dpg-cj97tfu3ttrc73abqleg-a.frankfurt-postgres.render.com/users_oba1?ssl=true
